### PR TITLE
Fix UTF8 decoding of mails

### PR DESCRIPTION
**Pull request by LinqLover**
Applying `#squeakToUtf8` multiple times until an error occurs has revealed the best results in Squeak Inbox Talk even though it sounds somehow dumb.

Closes https://github.com/hpi-swa-lab/squeak-inbox-talk/issues/34.

---

Reset all relevant caches in your image to explore the impact:

```smalltalk
SqhMailWrapper allSubInstancesDo: [:ea | ea removeProperty: #subject; removeProperty: #bodyText]
```

### CODE REVIEW

**Comment by stlutz** [comment]
Just to add an example: [This recent mail](https://lists.squeakfoundation.org/pipermail/squeak-dev/2021-September/216559.html) appears like undecoded UTF-8 on SqueakInboxTalk to me.

<details>
  <summary>The character used for indentation is still encoded as UTF-8</summary>

  image
</details>

I'd assume that this is supposed to be a [NO-BREAK SPACE](https://codepoints.net/U+00A0) (and my web browser also displays it as such), but was accidentally double-encoded in UTF-8 for some reason. Do we re-encode data somewehere that is already UTF-8? Or does the mail header maybe give hints as to such a re-encoding?

**Comment by stlutz** [comment]
Oh, also: Is there an example of a mail that is **not** double-encoded and actually produces an error when sent `#utf8ToSqueak` twice?

**Comment by LinqLover** [comment]
I'm afraid I cannot reproduce your example. The message from above looks well in my image - yes it does start with three nbsp characters followed by a normal space, but these characters are displayed correctly as a single glyph on my end. Did you install SqueakInboxTalk via Metacello recently? What is the timestamp of your `SqhMailWrapper >> #bodyText`? If you have installed SIT as expected, this patch should already be present and the timestamp should be `ct 7/8/2021 16:26`.

> Do we re-encode data somewehere that is already UTF-8? Or does the mail header maybe give hints as to such a re-encoding?

Fair questions which I unfortunately cannot answer ... 😆 However, apparently there is no metadata for this in the mail header:

image

> Oh, also: Is there an example of a mail that is **not** double-encoded and actually produces an error when sent `#utf8ToSqueak` twice?

If I remove the error check in the decode method and reset the caches (see snippet above), this message by gettimothy containing these terms fails, for example: `DocCustomHelpToOrg perfect`

PS: It's great to hear that someone else is using SIT! :-)

**Comment by stlutz** [comment]
> If you have installed SIT as expected, this patch should already be present

As it turns out, I have not 😅. I had already installed a much earlier version of SqueakInboxTalk that would not `self-update` itself, so I just unloaded the package and reinstalled it using the Metacello snippet. After unloading SqueakHistory too, clearing the github-cache and installing it all again, I think I now have a coherent installation. Let's hope.

**Comment by LinqLover** [comment]
I cannot even remember having released SIT before it had the self-update button ... You're clearly an early adopter. :-) If you identify any other issues, please let me know!

**Comment by stlutz** [comment]
> If I remove the error check in the decode method and reset the caches (see snippet above), this message by gettimothy containing these terms fails, for example: DocCustomHelpToOrg perfect

Hmm... interestingly enough that subject line actually contains unicode characters that should look very different if it was actually utf-8 encoded. My best guess would be that subject lines are not utf8-encoded and bodies are encoded twice. At least the following snippet ran successfully over my currently loaded messages:

```smalltalk
SqhMailmanAggregator messages do: [:each |
	each mailMessage bodyText utf8ToSqueak utf8ToSqueak].
```

It's ultimately not really important, since the code does work.

**Pull request merged**
